[package]
name = "app"
version = "0.1.0"
description = "wispr clone"
authors = ["You"]
license = "MIT"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
<<<<<<< HEAD
tauri = { version = "1.8.1", features = [ "api-all", "global-shortcut"] }
=======
serde_json = "1.0"
>>>>>>> f81bad704b3b6cef84039ce25aaf0019b595ac8f

tauri = { version = "1.8.3", features = [
  "api-all",
  "system-tray"
] }

enigo = "0.2"
log = "0.4"
env_logger = "0.11"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
